Froggo teams integration refactor and fixes
platanus/froggo pull request #274
Opened 2020-09-10 19:31 UTC by pfarellano

en este PR se agregan algunos detalles como:

- en la vista de equipos, además de mostrar los equipos a los que el usuario pertenece, se muestran los equipos de toda la organización
- se especificaron los errores, haciendo la diferencia entre bad_request y unauthorized 
- se movió el dropdown de nuevos integrantes hacia arriba en la vista de los equipos (show) y se agregó un contador de miembros

y se resolvió un pequeño bug que había porque la variable index que recibe la mutación REMOVE_MEMBER no estaba siendo asignada

2020-09-10 19:32 UTC, monkeyci commented on app/assets/stylesheets/app/froggo_teams.scss
> +    &:not(:first-child) {
**[stylelint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
Expected empty line before rule                                rule-empty-line-before

2020-09-10 19:32 UTC, monkeyci commented on app/assets/stylesheets/app/froggo_teams.scss
> +    color: $primary-color;;
**[stylelint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
Expected newline after ";" in a multi-line declaration block   declaration-block-semicolon-newline-after

2020-09-10 19:37 UTC, monkeyci commented on app/assets/stylesheets/app/froggo_teams.scss
> +
**[stylelint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
Unexpected whitespace at end of line   no-eol-whitespace

2020-09-11 16:25 UTC, mrafaeli requested changes
Se ve bien 👍  te dejo un par de comentarios chicos

2020-09-11 16:28 UTC, pfarellano commented on app/javascript/components/froggo-teams-list.vue
> +      console.log(notBelongedTeams.map(t => t.id));
ups ! gracias !!

2020-09-11 16:34 UTC, pfarellano commented on app/controllers/froggo_teams_controller.rb
> +    @organizations = user.get_organizations_with_teams
tengo una duda eso si, como puedo incluir en el  pluck los teams ? porque no quiero que me mande una lista de los teams con toda su info, solo quiero que me de los id de cada uno y su nombre , me cachai ?

2020-09-11 20:40 UTC, mrafaeli approved these changes

2020-09-11 20:49 UTC, merged