Update froggo teams show
platanus/froggo pull request #284
Opened 2020-09-24 19:23 UTC by pfarellano

Antes el path de froggo teams show, mostraba una vista con el equipo froggo team  (sus miembros y características) y además se podía editar el equipo desde ahí mismo. Ahora la idea es que existan 2 vistas separadas ... una que sea show y otra que sea edit. La idea es que show solo muestre al equipo y se puedan activar y desactivar sus miembros, y que edit permita editar las características del equipo como el nombre, miembros, etc.

En este PR está el nuevo "show", que por una parte ya no incluye los métodos de edición que antes incluía y por otra agrega una nueva funcionalidad que es la de activar o desactivar miembros del equipo, a través de un botón switch. La idea de esto último es que para cada equipo se pueda setear si un miembro está o no activo (por ejemplo se debería poder desactivar un miembro que está de vacaciones), lo que se hace a través del atributo "is_member_active" del modelo FroggoTeamMembership

Antes: 

![image](https://user-images.githubusercontent.com/37182412/94190233-36fd6080-fe82-11ea-8e78-54853d6e7b24.png)

Después:

![Captura de pantalla 2020-09-24 a la(s) 16 20 25](https://user-images.githubusercontent.com/37182412/94190309-4c728a80-fe82-11ea-9a4b-8cba712395d4.png)

2020-09-24 19:24 UTC, monkeyci commented on app/assets/stylesheets/app/switch.scss
> +.slider:before {
**[stylelint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
Expected double colon pseudo-element notation   selector-pseudo-element-colon-notation

2020-09-24 19:24 UTC, monkeyci commented on app/assets/stylesheets/app/switch.scss
> +  content: "";
**[stylelint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
Expected single quotes                          string-quotes

2020-09-24 19:24 UTC, monkeyci commented on app/assets/stylesheets/app/switch.scss
> +  background-color: white;
**[stylelint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
Unexpected named color "white"                  color-named

2020-09-24 19:24 UTC, monkeyci commented on app/assets/stylesheets/app/switch.scss
> +input:checked + .slider:before {
**[stylelint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
Expected double colon pseudo-element notation   selector-pseudo-element-colon-notation

2020-09-24 20:11 UTC, DiegoAndai requested changes
Te dejo unas propuestas de cambio a ver que opinas. También una duda, me genera harta ansiedad la especificidad del CSS, hay hartas medidas como `56px`, `21px`. Me genera inquietud porque estas decisiones son muy difíciles de mantener consistentes, y si no se mantienen consistentes el estilo de la página se empieza a desordenar muy rápido. Por eso mi pregunta es si han conversado la posibilidad de empezar a ocupar tailwind? no para hacer un refactor de todo, si no que gradualmente empezar a incorporarlo.

2020-09-24 20:11 UTC, DiegoAndai commented on app/controllers/api/v1/froggo_teams_controller.rb
> +              changed_members_ids: [])
¿Entiendo que `changed_members_ids` es para cambiar el estado de activación? No se si me parece muy intuitivo los controles de activar/desactivar. Principalmente me parece raro que se pueda hacer de dos lugares distintos, si van a tener la activación en el show la sacaría del edit. Es mi opinión personal no se que te parece.

2020-09-24 20:11 UTC, DiegoAndai commented on app/controllers/froggo_teams_controller.rb
> +    @members_state = get_members_state(@froggo_team_members, @froggo_team)
Porque va separado el estado de los miembros? me parece un poco raro, creo que si ya tienes @froggo_team_members, esos members deberían ir con la información de si cada uno es activo o no.

2020-09-24 20:11 UTC, DiegoAndai commented on app/javascript/components/froggo-team-show.vue
> +      membersState: { ...this.usersState },
Creo que

1. ocupar membersState y usersState puede causar confusión, debería quedar o memberstState o usersState en todos lados, pero en realidad no ocuparía ninguna porque:
2. de nuevo, no ocuparía una variable separada para el estado de cada miembro, creo que debería ser algo como que por cada user en froggoTeamsUsers se pueda hacer user.active, tener estas dos variables que son muy parecidas genera una duplicación de código que puede ser difícil de entender y mantener

2020-09-24 20:11 UTC, DiegoAndai commented on app/views/froggo_teams/show.html.erb
> +          :users-state="<%= @members_state.to_json %>"
Aca me parece que el prop debiese ser members-state para mantenerlo consistente

2020-09-24 20:14 UTC, pfarellano commented on db/migrate/20200923140921_add_member_active_to_froggo_team_memberships.rb
> +    change_column_default :froggo_team_memberships, :is_member_active, true
sii eso fue lo primero q intenté pero no me dejó :( ... me tiraba un error, algo como strong migrations

2020-09-24 20:39 UTC, pfarellano commented on app/controllers/api/v1/froggo_teams_controller.rb
> +              changed_members_ids: [])
sii ! la idea es que solamente esté en el show ;) el edit aún lo estoy haciendo

2020-09-24 20:40 UTC, pfarellano commented on app/controllers/froggo_teams_controller.rb
> +    @members_state = get_members_state(@froggo_team_members, @froggo_team)
buen punto ! voy a hacer un hash que lo incluya

2020-09-24 20:41 UTC, pfarellano commented on app/javascript/components/froggo-team-show.vue
> +      membersState: { ...this.usersState },
toda la razón

2020-09-24 20:43 UTC, pfarellano commented on app/views/froggo_teams/show.html.erb
> +          :users-state="<%= @members_state.to_json %>"
es que ya tenía una data que se llamaba así entonces no se puede tener una data y una prop q se llamen iguales jajaj en todo caso, si hago lo que me propusiste arriba de incluir la información en cada usuario no hay drama porq ya no necesitaría la prop

2020-09-25 17:23 UTC, monkeyci commented on app/controllers/froggo_teams_controller.rb
> +        active: get_member_activation(member, froggo_team),
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
Style/TrailingCommaInHashLiteral: Avoid comma after the last item of a hash.

2020-09-25 20:40 UTC, DiegoAndai approved these changes

2020-09-28 13:08 UTC, merged