Feat description
platanus/froggo pull request #317
Opened 2020-12-28 14:23 UTC by fprebolledo

### Contexto
Cuando se va al perfil de una persona en froggo se debe ver una descripción de esta, si me encuentro en mi propio perfil y no cuento con una descripción debo poder crearla, si ya tengo una, se debe poder editar haciendo doble click sobre esta.

### Qué se está haciendo

Se agrega un atributo descripción al github user, además de la ruta api/github_users/:id/update_description, la cual es utilizada en el componente user-read-more.vue, que se encarga de visualizar, crear y editar la descripción del usuario.

#### En particular hay que revisar

2020-12-28 14:30 UTC, monkeyci commented on app/controllers/api/v1/github_users_controller.rb
> +    params.permit(:org_id, :team_id, :github_login, :from, :to, :month_limit, :froggo_team,
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Layout/TrailingWhitespace: Trailing whitespace detected.

2020-12-28 19:00 UTC, difernandez requested changes
Buena! Ahí dejé comentarios y algunas cosas que cambiar. En particular creo que es importante lo del controlador y un par de cosas del componente

2020-12-28 21:11 UTC, monkeyci commented on app/javascript/components/profile-description.vue
> +      v-if="!readMoreActivated && !editDescription"
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected indentation of 8 spaces but found 6 spaces  vue/html-indent

2020-12-28 21:11 UTC, monkeyci commented on app/javascript/components/profile-description.vue
> +      v-if="readMoreActivated & !editDescription"
⚠️ **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected indentation of 8 spaces but found 6 spaces  vue/html-indent

2020-12-29 11:51 UTC, difernandez approved these changes

2020-12-29 11:58 UTC, merged