Profile show tags
platanus/froggo pull request #319
Opened 2021-01-04 20:19 UTC by fprebolledo

### Contexto
Se quiere poder visualizar los tags de los usuarios, además de poder añadir y eliminar los tags propios.

### Qué se está haciendo
Se agregan 2 componentes user-tags.vue y tags-show.vue, donde el el primero se encarga del comportamiento de agregar y eliminar tags mediante un modal y el segundo se utiliza para visualizar los tags tanto en el perfil como en la caja de agregaciones en el modal. 

#### En particular hay que revisar

2021-01-04 20:20 UTC, monkeyci commented on app/assets/stylesheets/app/tags-show.scss
> +    border-style: none;
**[stylelint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected value "none" for property "border-style"   declaration-property-value-blacklist

2021-01-04 20:20 UTC, monkeyci commented on app/assets/stylesheets/app/user_tags.scss
> +  -webkit-transform: translate(-50%, -50%);
**[stylelint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected vendor-prefix "-webkit-transform"    property-no-vendor-prefix

2021-01-04 20:20 UTC, monkeyci commented on app/assets/stylesheets/app/user_tags.scss
> +  -moz-transform: translate(-50%, -50%);
**[stylelint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected vendor-prefix "-moz-transform"       property-no-vendor-prefix

2021-01-04 20:20 UTC, monkeyci commented on app/assets/stylesheets/app/user_tags.scss
> +  .profile-tag {
**[stylelint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Expected empty line before rule                 rule-empty-line-before

2021-01-04 20:20 UTC, monkeyci commented on app/assets/stylesheets/app/user_tags.scss
> +      border: none;
**[stylelint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected value "none" for property "border"   declaration-property-value-blacklist

2021-01-05 15:17 UTC, gmq requested changes

2021-01-05 15:17 UTC, gmq commented on app/assets/stylesheets/app/user_tags.scss
> +.modal-overlay {
Valdrá la pena hacer que este modal sea un componente independiente que permita mostrar contenido genérico en vez de estar atado a `user-tags`?

2021-01-05 15:17 UTC, gmq commented on app/javascript/components/user-tags.vue
> +      axios.patch(`/api/github_users/${String(this.githubSession.user.id)}`, {
Es necesario convertir el id a string?

2021-01-05 15:17 UTC, gmq commented on app/javascript/components/user-tags.vue
> +          this.haveTags = this.myTags.length !== 0;
Creo que esto debería ser un `computed` en vez de setearlo cada vez que se cambia la propiedad

2021-01-05 15:43 UTC, fprebolledo commented on app/assets/stylesheets/app/user_tags.scss
> +.modal-overlay {
no sé si valga mucho la pena, ya que se pueden hacer con la lirería de vue, de manera más fácil (lo supe tarde), pero si lo recomiendas, puedo hacerlo. Que crees?

2021-01-05 15:45 UTC, gmq commented on app/assets/stylesheets/app/user_tags.scss
> +.modal-overlay {
Ah, en ese caso no vale la pena. Dejar en alguna parte anotado nomás que hay que migrar a la librería si no lo quieres incluir en este PR.

2021-01-05 17:47 UTC, gmq requested changes
Dejé varios comentarios pero en general falta revisar la implementación de BEM.
En https://la-guia.platan.us/stack/css/bem y los links en el footer puedes encontrar más información.

2021-01-05 17:47 UTC, gmq commented on app/assets/stylesheets/app/tags-show.scss
> +.tag__container {
Cuál es el bloque acá?

2021-01-05 17:47 UTC, gmq commented on app/assets/stylesheets/app/tags-show.scss
> +  .tag__name {
En BEM no deberían haber clases anidadas.

2021-01-05 18:07 UTC, fprebolledo commented on app/assets/stylesheets/app/tags-show.scss
> +.btn__img {
no es btn?

2021-01-05 18:17 UTC, gmq commented on app/assets/stylesheets/app/tags-show.scss
> +.btn__img {
Claro, y está bien definido como element pero la idea de BEM es que debería haber un bloque que sería el contenedor y elements serían lo que está adentro.

En el html está así:
```vue
    <button
      class="btn__modal btn__profile"
    >
      <img
        class="btn__img"
      >
    </button>
```

Para que sea BEM válido debería ser algo así:
```
    <button class="btn">
      <img
        class="btn__img"
      >
    </button>
```
Siendo `btn` lo que tiene los estilos del botón

2021-01-06 14:06 UTC, gmq approved these changes
Hay cosas que hubiera definido directamente en el template (`dropdownTitle` o `noTagsMessage`) pero

2021-01-06 14:13 UTC, merged