Select con buscador para asignar revisor en PR
platanus/froggo pull request #335
Opened 2021-02-08 12:43 UTC by jdmizunuma

## Contexto
Froggo es un proyecto interno para hacer lo más surtida posible la corrección de pull requests (PR's). Creemos que los PR's son una fuerte herramienta de transmisión de conocimiento de desarrollo y formas de abordar los problemas.
La aplicación tiene una grilla por organizaciones donde se puede ver todos los PR's enviados históricamente entre personas,  y posee una vista personal donde se recomienda a quiénes mandar el siguiente PR y a quiénes evitar (recomendador).
La idea es potenciar la vista personal para que los desarrolladores solo deban ingresar a esta única vista.

## Objetivo
Del pitch: Que los usuarios puedan asignar un PR desde su Froggo (puede ser en el perfil o una vista/modal especial).
De este PR: Que se muestre la foto de perfil, nombre de usuario y color de recomendación de los usuarios a los que se les puede asignar un PR (dentro del select).

## Motivación
Ha sido mencionado varias veces que sería cómodo poder asignar un PR desde Froggo directamente. Esto evitaría estar saltando de una página a otra para asignar un PR. En cambio permitiría simplificar el flujo.

## Qué se está haciendo
- Se hace un refactor del nombre de un componente vue. Este se muesta por cada PR abierto del usuario logueado (pending-pr -> open-pr).
- Se agrega la componente _vue-select_ al proyecto y se utiliza en _open-pr.vue_ para que se muestre la foto, el username y el color de recomendación (para cada usuario al que se le puede asignar el PR).
- Se agrega vue-select al text de _open-pr.vue_
## Revisar
- ¿Son los nombres explicativos?
- ¿Están los colores, fonts, y tamaños bien?
- ¿Debería testear algo más?

## Video

https://user-images.githubusercontent.com/44006272/107221104-f1d16980-69f1-11eb-809f-f4455df7d8a6.mov

2021-02-08 20:19 UTC, difernandez requested changes
Buena se ve bien, y me parece bien el cambio de nombre 👍 . Échale un ojo a lo que puse de la sintáxis deprecada y lo del método users

2021-02-08 20:19 UTC, difernandez commented on app/javascript/components/open-pr.vue
> +        <span slot="no-options">No hay coincidencias</span>
usar solo `slot` [está deprecado](https://vuejs.org/v2/guide/components-slots.html#Deprecated-Syntax), habría que usar `v-slot` o el shorthand `#`

2021-02-08 20:19 UTC, difernandez commented on app/javascript/components/open-pr.vue
> +        <template v-slot:option="option">
en vez de `v-slot:` [puede usar también "#"](https://vuejs.org/v2/guide/components-slots.html#Named-Slots-Shorthand)

2021-02-08 20:19 UTC, difernandez commented on app/javascript/components/open-pr.vue
> +    },
- Esto retorna algo, no recibe parámetros y se calcula a partir de un computed, por lo que lo movería a `computed` en vez de `methods`
- En vez de crear un arreglo y llenarlo con forEach, puedes retornar directo un map:
```
return this.recommendations.all.map(item => { ... });
```
- Por lo que veo esto solo "cameliza" las keys de cada elemento. Para eso puedes aprovechar que el proyecto tiene la librería `humps` y usar `camelizeKeys`

2021-02-09 12:14 UTC, difernandez approved these changes

2021-02-09 12:28 UTC, jdmizunuma commented
![](https://github.trello.services/images/mini-trello-icon.png) [Autocompletador para asignación de PR’s](https://trello.com/c/eHfTKmNH/267-autocompletador-para-asignaci%C3%B3n-de-prs)

2021-02-09 12:57 UTC, merged