Add prs reviewer
platanus/froggo pull request #338
Opened 2021-02-12 14:01 UTC by jdmizunuma

## Contexto
Se busca poder asignar revisores a pull requests abiertos.

## Qué se está haciendo
- Se crea servicio _AddReviewerToPullRequestService_. Este llama a la API de Github para agregar un nuevo revisor a un PR.
- Se crea _PullRequestReviewersController_ : Controlador que recibe la información del PR y del revisor que se quiere asignar, y llama al servicio mencionado anteriormente.
- _open-pr.vue_ editado para tener el id del PR, además del título.

## Revisar
- ¿Está bien que sea un servicio, o debería ser un command?
- ¿Es correcta la forma en que se envía la información desde vue hasta rails (usando axios para hacer un post)?
- ¿El test del _Service_ debería testear algo más?
- ¿El manejo de errores es suficiente?

2021-02-12 14:46 UTC, GabrielLyonB requested changes
En general me parece bien. Hay cosas que no tienes como saber que las hacemos distinto. 
Hay algunas cosas que es mejor evitarlo. Por ejemplo, el primer _commit_ es del _test_ de lo que incorporas en el segundo _commit_. Lo ideal sería que estén en orden.

2021-02-12 14:46 UTC, GabrielLyonB commented on spec/services/add_reviewer_to_pull_request_service_spec.rb
> +      service.call(reviewer)
acá no falta un `expect`? eso va a pasar pero qué estás esperando que pase?

2021-02-12 14:46 UTC, GabrielLyonB commented on app/services/add_reviewer_to_pull_request_service.rb
> +class AddReviewerToPullRequestService < PowerTypes::Service.new(:token, :pull_request)
Me suena a que debería ser un `Command`. Incluso puede ser dentro de un controlador depende cómo se esté llamando. Lo podemos conversar.

2021-02-12 14:46 UTC, GabrielLyonB commented on app/controllers/api/v1/pull_request_reviewers_controller.rb
> +  def fetch_pr
este método queda un poco mejor o más platanero así:
``` ruby
def pull_request
  @pull_request ||= PullRequest.find(permitted_params[:pull_request_id])
end
```

2021-02-12 14:46 UTC, GabrielLyonB commented on app/controllers/api/v1/pull_request_reviewers_controller.rb
> +    service = AddReviewerToPullRequestService.new(
confirmo el comentario anterior: me parece que esto debería estar acá dentro y no en un `Command` o `Service`.

2021-02-12 14:46 UTC, GabrielLyonB commented on app/controllers/api/v1/pull_request_reviewers_controller.rb
> +    params.require(:pull_request_reviewer).permit(:pullRequestId, :reviewer)
Esto debería llegar de-camelizado desde el front: onda `pull_request_id`.

2021-02-12 14:46 UTC, GabrielLyonB commented on app/javascript/components/open-pr.vue
> +    prName() {
no le cambiaría el nombre: mantendría `prTitle`

2021-02-12 14:46 UTC, GabrielLyonB commented on app/javascript/components/open-pr.vue
> +    id() {
lo mismo acá, mantendría `prId`

2021-02-12 14:46 UTC, GabrielLyonB commented on app/javascript/components/open-pr.vue
> +        axios.post('/api/pull_request_reviewer/add', { reviewer: this.reviewer.login, pullRequestId: this.id })
Esto de acá debería estar en un archivo tipo `api.js` o mejor aún, una carpeta como lo [hace mute](https://github.com/platanus/mute-meetings/tree/development/app/javascript/api). Este cambio se hará en un _pitch_ pero tal vez avanzar un poquito puede servir.
De todas maneras debería al menos estar en otro método para que no sea un método tan grande (`sumit()`). Además, como te comenté antes hay que decamelizar los parámetros antes de enviarlos al backend.

2021-02-12 14:46 UTC, GabrielLyonB commented on app/views/github_users/_profile_card.html.erb
> +          :pr="<%= pr.to_json %>"
Cómo se ordena visualmente cuándo hay más de un PR?

2021-02-15 14:35 UTC, monkeyci commented on app/javascript/components/open-pr.vue
> +import axios from 'axios';
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'axios' is defined but never used  no-unused-vars

2021-02-15 19:30 UTC, GabrielLyonB approved these changes
Te dejé un comentario mini! Esta super bien!

2021-02-15 19:30 UTC, GabrielLyonB commented on app/javascript/components/open-pr.vue
> +import ApiPullRequestReviewer from '../api/pull_request_reviewers';
debería ser en minúscula y me tinca mejor `pullRequestReviewerApi`

2021-02-15 19:30 UTC, GabrielLyonB commented on app/controllers/api/v1/pull_request_reviewers_controller.rb
> +  def request_reviewer(repository, number, reviewer)
en vez de number pondría `gh_number` me costó cachar que era

2021-02-15 19:30 UTC, GabrielLyonB commented on app/controllers/api/v1/pull_request_reviewers_controller.rb
> +      number,
lo mismo

2021-02-16 18:32 UTC, merged