Create Preference model
platanus/froggo pull request #384
Opened 2021-06-03 14:42 UTC by ankaph

### Contexto

En Froggo, actualmente las preferencias del usuario se guardan en el storage del navegador. Si un usuario cambia de navegador o usa la nueva extensión, las preferencias desaparecen por no estar guardadas en el backend.

### Qué se está haciendo

-  Se crea el modelo `Preference`, que contiene las preferencias de un usuario para una organización (`default_organization_id`), equipo (`default_team_id`) y el tiempo (`default_time`) con un enum para determinar los tiempos disponibles.
- Se agregan los tests de validación y relación.

2021-06-03 14:57 UTC, rjherrera requested changes

2021-06-03 14:57 UTC, rjherrera commented on app/models/preference.rb
> +  validates :default_time, presence: true
da un poco lo mismo, pero como tip, podi poner varios y presence: true al final, onda:
```ruby
validates :a, :b, :c, presence: true
```

Puede que se pase de las 100 así que quizás ignórame nomás

2021-06-03 14:57 UTC, rjherrera commented on spec/models/preference_spec.rb
> +RSpec.describe Preference, type: :model do
pondría el clásico spec de valid factory:

```ruby
  it 'has a valid factory' do
    expect(build(:preference)).to be_valid
  end
```

que de hecho en este caso te va a forzar a que la factory venga con valores por defecto

2021-06-03 15:01 UTC, ankaph commented
![](https://github.trello.services/images/mini-trello-icon.png) [Crear modelo para guardar las preferencias del usuario](https://trello.com/c/VcLx29Cb/291-crear-modelo-para-guardar-las-preferencias-del-usuario)

2021-06-04 13:50 UTC, rjherrera approved these changes

2021-06-04 13:53 UTC, merged