refactor(layout): sidebar and header component
platanus/froggo pull request #386
Opened 2021-06-17 13:13 UTC by vicholp

### Contexto
El rediseño de la pagina de recomendaciones incluye una sidebar para acceder al resto de vistas de Froggo.

https://www.figma.com/file/ZZvsjJJIkiHhX8NRVxRuXV/Froggo?node-id=598%3A11

### Qué se esta haciendo

- Se agrega plugin `inline-svg` de node, necesario en los nuevos componentes
- ​El header que ya existia se pasó a un componente de Vue
- Se crea un nuevo componente para la sidebar
- Los dos componentes anteriores, se incluyen en el layout de todas las vistas

#### En particular hay que revisar
​Dentro de `sidebar.vue` y de `header.vue`, tuve que usar `require('path').default`, para meter los svg. Vi que en otros proyectos no es necesario el `.default`, pero no cacho bien por que, ni como solucionarlo.

-----------
#### Info Adicional (pantallazos, links, fuentes, etc.)
![image](https://user-images.githubusercontent.com/28970593/122390624-35a82280-cf40-11eb-99ca-f7e88b2c1bc8.png)

2021-06-17 13:15 UTC, monkeyci commented on app/javascript/components/shared/sidebar.vue
> +}
🚫 **[eslint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing semicolon  semi

2021-06-22 14:27 UTC, difernandez requested changes
Puros detalles chicos, algunos probablemente vienen de antes igual.

Me parece raro lo del `.default`, pero no cacho que puede ser 🤔 . No tiene que ver con eso directamente, pero podrías agregar un poco de config al environment.js para evitar tener que poner todos los `../` al requerir assets. [Acá ejemplo en mute](https://github.com/platanus/mute-meetings/blob/development/config/webpack/environment.js). con esto sería solo `require('assets/blabla')`.

2021-06-22 14:27 UTC, difernandez commented on app/javascript/components/shared/header.vue
> +            slot="btn"
El atributo slot está deprecado, [acá la sintáxis actual](https://vuejs.org/v2/guide/components-slots.html#Named-Slots) y [acá un shorthand](https://vuejs.org/v2/guide/components-slots.html#Named-Slots-Shorthand)

2021-06-22 14:27 UTC, difernandez commented on app/javascript/components/shared/header.vue
> +      default: () => {},
acá el default debería retornar []

2021-06-22 14:27 UTC, difernandez commented on app/javascript/components/shared/sidebar.vue
> +      <div :class="`p-3 text-gray-500`">
acá es innecesario el v-bind y las ``

2021-06-22 14:27 UTC, difernandez commented on app/javascript/components/shared/sidebar.vue
> +          class="relative flex items-center"
creeo que el relative acá no es necesario

2021-06-22 14:27 UTC, difernandez commented on app/javascript/locales/es.js
> +        closeSession: 'Cerrar sesion',
*sesión

2021-06-22 14:27 UTC, difernandez commented on app/views/layouts/application.html.erb
> +            :feed-path="`<%= organization_pull_requests_path(organization_name: @github_session.organizations.first[:login]) %>`"
Si vas a pasar un string como prop desde rails, puedes omitir el `:` y pasar solo el string sin las ``:

```
teams-path="<%= github_user_froggo_teams_path(github_user_id: @github_session.user.id) %>"
```

2021-06-23 20:51 UTC, difernandez approved these changes

2021-06-23 21:27 UTC, merged

2021-07-15 13:32 UTC, iaacosta commented
![](https://github.trello.services/images/mini-trello-icon.png) [Sidebar](https://trello.com/c/3WocqkF5/288-sidebar)